spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 5
      properties:
        enable.idempotence: true
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

outbox:
  kafka:
    manage-topics: true
    topics:
      - key: outbox-events
        name: outboxEvents
        partitions: 3
        replicas: 1
      - key: outbox-dlq
        name: outboxEvents.dlq
        partitions: 3
        replicas: 1
  publisher:
    batch-size: 10
    delay-ms: 10000ms  # 10 Seconds
    claim-lease: 30s


server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: WARN
    org.example.auth: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
