{
 "title": "Redis Overview",
 "description": "redis_exporter for redis",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(redis_up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ops/sec[3m]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(redis_commands_processed_total{instance=\"$instance\"}[3m])/180"
    }
   ]
  },
  {
   "title": "Network",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory "
    },
    {
     "expr": "redis_memory_used_peak_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory Peak"
    },
    {
     "expr": "redis_memory_used_lua_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory Lua"
    },
    {
     "expr": "redis_memory_used_dataset_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory Dataset"
    },
    {
     "expr": "redis_memory_used_overhead_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory Overhead"
    },
    {
     "expr": "redis_memory_used_rss_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory Rss"
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{instance=\"$instance\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "connected clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Redis Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{instance=\"$instance\"}",
     "legendFormat": "{{redis_version}}"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Number of keys",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_db_keys{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "keys",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(redis_expired_keys_total{instance=\"$instance\"}[3m])",
     "legendFormat": "expired keys"
    },
    {
     "expr": "rate(redis_evicted_keys_total{instance=\"$instance\"}[3m])",
     "legendFormat": "evicted keys"
    }
   ]
  },
  {
   "title": "keys",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_keyspace_hits_total{instance=\"$instance\"}",
     "legendFormat": "Hits"
    },
    {
     "expr": "redis_keyspace_misses_total{instance=\"$instance\"}",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Maxmemory Policy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{instance=\"$instance\"}",
     "legendFormat": "{{maxmemory_policy}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (rate(redis_cpu_sys_children_seconds_total{instance=\"$instance\"}[5m]) + rate(redis_cpu_sys_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "System"
    },
    {
     "expr": "100 * (rate(redis_cpu_user_children_seconds_total{instance=\"$instance\"}[5m]) + rate(redis_cpu_user_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=\"$instance\"} [5m]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Conns/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(redis_connections_received_total{instance=\"$instance\"}[5m]) ",
     "legendFormat": "Inbound"
    }
   ]
  },
  {
   "title": "Keys / DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_db_keys{instance=\"$instance\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Average TTL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_db_avg_ttl_seconds{instance='$instance'}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Expired / Evicted keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(redis_expired_keys_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Expired"
    },
    {
     "expr": "rate(redis_evicted_keys_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(redis_keyspace_hits_total{instance=\"$instance\"}[5m])   / (rate(redis_keyspace_misses_total{instance=\"$instance\"}[5m]) + rate(redis_keyspace_hits_total{instance=\"$instance\"}[5m])) ",
     "legendFormat": "Hit"
    }
   ]
  },
  {
   "title": "Connections usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}",
     "legendFormat": "Clients"
    },
    {
     "expr": "redis_config_maxclients{instance=\"$instance\"}",
     "legendFormat": "Max Clients"
    }
   ]
  },
  {
   "title": "Blocked and Rejected clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_blocked_clients{instance=\"$instance\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "rate(redis_rejected_connections_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{instance=\"$instance\"}[5m])) / sum(rate(redis_commands_processed_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Slowlog increment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(redis_slowlog_length{instance=\"$instance\"}[5m])",
     "legendFormat": "Response Time"
    }
   ]
  }
 ]
}