package org.example.auth.authorisation.domain;

public enum AuthorisationEventReason {
  NONE,
  INSUFFICIENT_FUNDS,
  ACCOUNT_LOCKED,
  ACCOUNT_INACTIVE,
  CURRENCY_MISMATCH,
  INVALID_AMOUNT,
  INVALID_STATE,
  AUTHORISATION_NOT_FOUND,
  DUPLICATE_REQUEST,
  FRAUD_DECLINED,
  CUSTOMER_REQUEST,
  MERCHANT_REQUEST,
  EXPIRED,
  TIMEOUT,
  SYSTEM_ERROR
}
